apiVersion: v2
description: A Helm chart for petclinic application
home: https://epam.github.io/edp-install/
name: petclinic
type: application
version: 2.6.0-SNAPSHOT
appVersion: 2.6.0-SNAPSHOT
keywords:
  - edp
  - codebase
  - operator
  - pipelines
  - jira
  - ci
  - cd
  - docker
  - image
  - promote
  - git
  - gerrit
  - github
  - gitlab
maintainers:
  - name: sergk
    url: https://github.com/SergK
sources:
  - https://github.com/sergk/petclinic
